/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAProposRouteImport } from './routes/_site/a-propos'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteEquipeRouteImport } from './routes/_site/equipe'
import { Route as SitePartenairesRouteImport } from './routes/_site/partenaires'
import { Route as SiteRealisationsRouteImport } from './routes/_site/realisations'
import { Route as SiteServicesRouteImport } from './routes/_site/services'
import { Route as SiteActualitesIndexRouteImport } from './routes/_site/actualites.index'
import { Route as SiteActualitesSlugRouteImport } from './routes/_site/actualites.$slug'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAProposRoute = SiteAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEquipeRoute = SiteEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePartenairesRoute = SitePartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteRealisationsRoute = SiteRealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteActualitesIndexRoute = SiteActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteActualitesSlugRoute = SiteActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/a-propos': typeof SiteAProposRoute
  '/contact': typeof SiteContactRoute
  '/equipe': typeof SiteEquipeRoute
  '/partenaires': typeof SitePartenairesRoute
  '/realisations': typeof SiteRealisationsRoute
  '/services': typeof SiteServicesRoute
  '/actualites/$slug': typeof SiteActualitesSlugRoute
  '/actualites/': typeof SiteActualitesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/a-propos': typeof SiteAProposRoute
  '/contact': typeof SiteContactRoute
  '/equipe': typeof SiteEquipeRoute
  '/partenaires': typeof SitePartenairesRoute
  '/realisations': typeof SiteRealisationsRoute
  '/services': typeof SiteServicesRoute
  '/': typeof SiteIndexRoute
  '/actualites/$slug': typeof SiteActualitesSlugRoute
  '/actualites': typeof SiteActualitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_site/a-propos': typeof SiteAProposRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/equipe': typeof SiteEquipeRoute
  '/_site/partenaires': typeof SitePartenairesRoute
  '/_site/realisations': typeof SiteRealisationsRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/actualites/$slug': typeof SiteActualitesSlugRoute
  '/_site/actualites/': typeof SiteActualitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/a-propos'
    | '/contact'
    | '/equipe'
    | '/partenaires'
    | '/realisations'
    | '/services'
    | '/actualites/$slug'
    | '/actualites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/a-propos'
    | '/contact'
    | '/equipe'
    | '/partenaires'
    | '/realisations'
    | '/services'
    | '/'
    | '/actualites/$slug'
    | '/actualites'
  id:
    | '__root__'
    | '/_site'
    | '/auth'
    | '/_site/a-propos'
    | '/_site/contact'
    | '/_site/equipe'
    | '/_site/partenaires'
    | '/_site/realisations'
    | '/_site/services'
    | '/_site/'
    | '/_site/actualites/$slug'
    | '/_site/actualites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/a-propos': {
      id: '/_site/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof SiteAProposRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/equipe': {
      id: '/_site/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof SiteEquipeRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/partenaires': {
      id: '/_site/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof SitePartenairesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/realisations': {
      id: '/_site/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof SiteRealisationsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/actualites/': {
      id: '/_site/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof SiteActualitesIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/actualites/$slug': {
      id: '/_site/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof SiteActualitesSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteAProposRoute: typeof SiteAProposRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteEquipeRoute: typeof SiteEquipeRoute
  SitePartenairesRoute: typeof SitePartenairesRoute
  SiteRealisationsRoute: typeof SiteRealisationsRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteActualitesSlugRoute: typeof SiteActualitesSlugRoute
  SiteActualitesIndexRoute: typeof SiteActualitesIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteAProposRoute: SiteAProposRoute,
  SiteContactRoute: SiteContactRoute,
  SiteEquipeRoute: SiteEquipeRoute,
  SitePartenairesRoute: SitePartenairesRoute,
  SiteRealisationsRoute: SiteRealisationsRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteActualitesSlugRoute: SiteActualitesSlugRoute,
  SiteActualitesIndexRoute: SiteActualitesIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
